services:
  postgres-db:
    image: postgres:latest
    restart: 'always'
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=currency_converter_db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  currency-converter:
    build:
      context: ./
      dockerfile: 'Dockerfile'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/currency_converter_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - 'postgres-db'
    restart: 'always'
    container_name: 'app'
    ports:
      - '8080:8080'

volumes:
  pg-data:
