spring:
  #  sql:
  #    init:
  #      mode: always
  #      schema-locations: classpath:schema.sql
  #      data-locations: classpath:data.sql

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/currency_converter_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: info
